#!/bin/bash
# Claude Code on the web 用の SessionStart フック。
#
# このプロジェクトは Gradle の "Daemon JVM discovery" 機能
# (gradle/gradle-daemon-jvm.properties) で JDK 25 を要求しているが、
# Claude Code on the web のサンドボックス環境には JDK 25 がプリインストールされておらず、
# JDK の自動取得先である api.foojay.io へのアクセスも既定のネットワークポリシーでは
# 許可されていないため、そのままでは ./gradlew の起動時点で失敗する。
# このフックは、要求バージョンのJDKが見つからずネットワークからも取得できない場合に限り、
# ローカルにインストール済みのJDKバージョンへ一時的に読み替える。
#
# また、AGP (Android Gradle Plugin) や AndroidX 依存関係の解決には
# Google の Maven リポジトリ (dl.google.com) へのアクセスが必須であり、
# ここが到達不能な場合は本プロジェクトのどのモジュールに対する ./gradlew タスクも
# (ルートの build.gradle.kts が常に AGP プラグインを評価するため) 失敗する。
# その場合はビルドを試みず、原因と対処法を分かりやすく警告として出力するだけに留める。
set -uo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$PROJECT_DIR" || exit 0

DAEMON_JVM_PROPS="gradle/gradle-daemon-jvm.properties"

# https://<host>/ へ実際に接続できるかどうかを確認する。
# HTTPステータス(403/404等)はサーバーまで到達できた証拠なので成功扱い、
# プロキシのCONNECT拒否やDNS失敗などネットワークレベルの失敗のみを不可到達とする。
is_reachable() {
  curl -sS -o /dev/null -m 6 "https://$1/" >/dev/null 2>&1
}

# ローカルにインストール済みのJDKメジャーバージョン一覧を降順で列挙する。
installed_jdk_majors() {
  local found=0
  if [ -d /usr/lib/jvm ]; then
    for dir in /usr/lib/jvm/*/; do
      local java_bin="${dir}bin/java"
      if [ -x "$java_bin" ]; then
        local ver
        # `java` 実行時に JAVA_TOOL_OPTIONS 由来の "Picked up ..." 行が
        # バージョン行より前に出ることがあるため、head -n1 ではなく
        # 全行から最初にマッチしたバージョン番号を拾う。
        ver=$("$java_bin" -version 2>&1 | grep -m1 -oE '"[0-9]+' | tr -d '"')
        if [ -n "$ver" ]; then
          echo "$ver"
          found=1
        fi
      fi
    done
  fi
  if [ "$found" -eq 0 ] && command -v java >/dev/null 2>&1; then
    java -version 2>&1 | grep -m1 -oE '"[0-9]+' | tr -d '"'
  fi
}

INSTALLED_MAJORS=$(installed_jdk_majors | sort -rn | uniq)
HIGHEST_INSTALLED=$(echo "$INSTALLED_MAJORS" | head -n1)

if [ -f "$DAEMON_JVM_PROPS" ] && [ -n "$HIGHEST_INSTALLED" ]; then
  REQUIRED_VERSION=$(grep -oE '^toolchainVersion=[0-9]+' "$DAEMON_JVM_PROPS" | cut -d= -f2)

  HAS_MATCH=false
  for major in $INSTALLED_MAJORS; do
    if [ "$major" = "$REQUIRED_VERSION" ]; then
      HAS_MATCH=true
      break
    fi
  done

  if [ "$HAS_MATCH" = false ]; then
    if is_reachable "api.foojay.io"; then
      echo "[session-start] Gradle Daemon JVM に要求されている JDK ${REQUIRED_VERSION} はローカルに無いが、api.foojay.io へ到達できるため自動取得に委ねる。"
    else
      echo "[session-start] Gradle Daemon JVM が要求する JDK ${REQUIRED_VERSION} が見つからず、自動取得先 (api.foojay.io) にも到達できないため、"
      echo "[session-start] ${DAEMON_JVM_PROPS} をこのセッション用にインストール済みの JDK ${HIGHEST_INSTALLED} へ一時的に読み替える(リポジトリへはコミットしないこと)。"
      cat > "$DAEMON_JVM_PROPS" << EOF
#This file is generated by updateDaemonJvm
toolchainVersion=${HIGHEST_INSTALLED}
EOF
    fi
  fi
fi

if command -v java >/dev/null 2>&1 && [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  JAVA_HOME_DETECTED=$(dirname "$(dirname "$(readlink -f "$(command -v java)")")")
  echo "export JAVA_HOME=\"${JAVA_HOME_DETECTED}\"" >> "$CLAUDE_ENV_FILE"
fi

if is_reachable "dl.google.com"; then
  echo "[session-start] dl.google.com へ到達可能。Gradle依存関係の解決を事前に行いキャッシュを温める。"
  timeout 280 ./gradlew help --no-daemon -q || \
    echo "[session-start] warm-up (./gradlew help) が失敗したが、セッションはそのまま起動する。"
else
  cat << 'EOF'
[session-start] 警告: dl.google.com (Google Maven リポジトリ) へ到達できない。
[session-start] このプロジェクトは :app / :app:core / :app:feature:* / :data が
[session-start] Android Gradle Plugin (AGP) を利用しており、ルートの build.gradle.kts が
[session-start] 常に AGP プラグインを評価するため、dl.google.com が到達不能な間は
[session-start] ./gradlew の実行対象に関わらず (:domain のみを指定した場合でも) 失敗する。
[session-start] ビルド/テスト/lintを動かすには、この環境(Environment)のネットワークポリシーを
[session-start] "Full network access" に変更するか、dl.google.com を許可するカスタムアローリストに
[session-start] 追加してください。詳細: https://code.claude.com/docs/en/claude-code-on-the-web
EOF
fi

exit 0
